# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from pathlib import Path

# Add the parent directory to the path so we can import the package
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

# Project information
project = "repo-sapiens"
copyright = "2025, savorywatt"
author = "savorywatt"
release = "0.0.2"
version = "0.0.2"

# General configuration
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.doctest",
]

# Autodoc configuration
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "show-inheritance": True,
}

autosummary_generate = True
autosummary_generate_overwrite = True

# Napoleon settings for docstring parsing
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that are also relative to
# the source directory itself.
exclude_patterns = []

# The theme to use for HTML and HTML Help pages.
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and usually documented in the theme's
# documentation.
html_theme_options = {
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "style_external_links": False,
    "vcs_pageview_mode": "blob",
    "style_nav_header_background": "#2980B9",
    # Toc options
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the built documentation
# in the build/_static directory.
html_static_path = ["_static"]

# Custom HTML context
html_context = {
    "display_github": True,
    "github_user": "savorywatt",
    "github_repo": "repo-sapiens",
    "github_version": "main",
    "conf_py_path": "/docs/source/",
}

# Intersphinx configuration
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Doctest configuration
doctest_default_flags = (
    1  # Verbose
    | 2  # Ellipsis
    | 4  # NORMALIZE_WHITESPACE
    | 8  # IGNORE_EXCEPTION_DETAIL
)

# Sphinx source suffix
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# Language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# Add any extra paths that contain custom files (e.g. robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the build directory when it is built.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at the bottom
# of every page. Use the strftime format string to format the timestamp.
html_last_updated_fmt = "%b %d, %Y"

# Optional MyST configuration if using Markdown
# rst_prolog = """
# .. include:: <isonum.txt>
# """
