name: Example - Using Pre-built Artifacts

# This workflow demonstrates how to use the pre-built artifacts from build-artifacts.yaml
# This is MUCH faster than rebuilding the package every time

on:
  issues:
    types: [labeled]

jobs:
  # Process issue using pre-built wheel
  process-with-wheel:
    name: Process Issue (Using Wheel)
    if: gitea.event.label.name == 'needs-planning'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code (for config files only)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download pre-built wheel
        uses: actions/download-artifact@v3
        with:
          name: sapiens-wheel
          path: dist/
        continue-on-error: true

      - name: Install from wheel (if available) or from source
        run: |
          if [ -f dist/*.whl ]; then
            echo "✅ Using pre-built wheel (fast!)"
            pip install dist/*.whl
          else
            echo "⚠️ No wheel artifact found, installing from source (slower)"
            pip install -e .
          fi

      - name: Run sapiens
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.BUILDER_GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.BUILDER_CLAUDE_API_KEY }}
        run: |
          sapiens process-issue --issue ${{ gitea.event.issue.number }}

  # Process issue using pre-built Docker image
  process-with-docker:
    name: Process Issue (Using Docker)
    if: gitea.event.label.name == 'execute'
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp/
        continue-on-error: true

      - name: Load Docker image
        run: |
          if [ -f /tmp/sapiens-image.tar ]; then
            echo "✅ Using pre-built Docker image (fast!)"
            docker load < /tmp/sapiens-image.tar
          else
            echo "⚠️ No Docker artifact found, building image (slower)"
            docker build -t repo-sapiens:latest .
          fi

      - name: Run sapiens in Docker
        env:
          GITEA_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          CLAUDE_API_KEY: ${{ secrets.BUILDER_CLAUDE_API_KEY }}
        run: |
          docker run --rm \
            -e AUTOMATION__GIT_PROVIDER__BASE_URL="${{ secrets.BUILDER_GITEA_URL }}" \
            -e AUTOMATION__GIT_PROVIDER__API_TOKEN="$GITEA_TOKEN" \
            -e AUTOMATION__REPOSITORY__OWNER="${{ gitea.repository_owner }}" \
            -e AUTOMATION__REPOSITORY__NAME="${{ gitea.repository }}" \
            -e AUTOMATION__AGENT_PROVIDER__API_KEY="$CLAUDE_API_KEY" \
            -v ${{ gitea.workspace }}:/workspace \
            repo-sapiens:latest \
            process-issue --issue ${{ gitea.event.issue.number }}
