name: Plan Approved

# Triggers when 'approved' label is added to a proposal
on:
  issues:
    types: [labeled]

jobs:
  create-tasks:
    name: Create Tasks from Approved Plan
    if: gitea.event.label.name == 'approved' && contains(gitea.event.issue.labels.*.name, 'proposed')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILDER_GITEA_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install sapiens
        run: pip install -e .

      - name: Process approved plan
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.BUILDER_GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.BUILDER_CLAUDE_API_KEY }}
        run: |
          echo "✅ Processing approved plan for issue #${{ gitea.event.issue.number }}"
          sapiens process-issue --issue ${{ gitea.event.issue.number }}

      - name: Comment on completion
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BUILDER_GITEA_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎯 **Tasks created!**\n\nThe plan has been broken down into executable tasks. Tasks will be automatically executed.\n\n🤖 Posted by Builder Automation'
            })
