# Sapiens Automation Daemon for Gitea Actions
#
# This workflow runs repo-sapiens periodically to process issues automatically
# using a local Ollama instance for AI processing.
#
# Required secrets:
#   - SAPIENS_GITEA_TOKEN: Gitea API token with repo/issue access

name: Sapiens Daemon

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger

env:
  CONFIG_FILE: sapiens_config.ci.yaml

jobs:
  process-pending:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install repo-sapiens from source
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Verify installation
        run: |
          sapiens --version || echo "Version check failed, continuing..."
          sapiens --help

      - name: Process all pending issues
        env:
          # Git provider credentials
          GITEA_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          GITEA_API_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          # Gitea server URL (for API calls)
          GITEA_URL: ${{ gitea.server_url }}
        run: |
          echo "Using config: $CONFIG_FILE"
          echo "Server URL: $GITEA_URL"
          sapiens --config "$CONFIG_FILE" process-all --log-level DEBUG

      - name: Upload state artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workflow-state-${{ gitea.run_number }}
          path: .sapiens/state/
          retention-days: 7
          if-no-files-found: ignore
