name: Automation Daemon

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  process-pending:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -e .

      - name: Process all pending issues
        env:
          GITEA_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          CLAUDE_API_KEY: ${{ secrets.BUILDER_CLAUDE_API_KEY }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.BUILDER_CLAUDE_API_KEY }}
        run: |
          automation process-all --log-level INFO

      - name: Check for stale workflows
        run: |
          automation check-stale --max-age-hours 24

      - name: Upload state artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: workflow-state
          path: .automation/state/
          retention-days: 7
