name: Complete CI/CD Example

# This workflow demonstrates the complete builder automation in CI/CD
# It processes issues, creates plans, implements tasks, reviews code, runs QA, and merges

on:
  issues:
    types: [opened, labeled, edited]
  pull_request:
    types: [opened, synchronize, labeled]
  schedule:
    # Run every hour to process pending work
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual trigger
    inputs:
      issue_number:
        description: 'Issue number to process (leave empty for all)'
        required: false
        type: number

jobs:
  # Job 1: Build and validate the automation package
  build:
    name: Build Automation Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Validate package
        run: |
          python -c "from automation.config.settings import AutomationSettings; print('✓ Package OK')"
          automation --help

      - name: Cache automation package
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-automation-${{ hashFiles('pyproject.toml') }}

  # Job 2: Process issues with 'needs-planning' label
  process-planning:
    name: Process Planning Issues
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'issues' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install automation
        run: pip install -e .

      - name: Process planning issues
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          AUTOMATION__WORKFLOW__MAX_CONCURRENT_TASKS: 3
        run: |
          if [ -n "${{ github.event.inputs.issue_number }}" ]; then
            echo "Processing specific issue #${{ github.event.inputs.issue_number }}"
            automation process-issue --issue ${{ github.event.inputs.issue_number }}
          else
            echo "Processing all planning issues"
            automation process-all --tag needs-planning
          fi

      - name: Upload state
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: automation-state
          path: .automation/state/

  # Job 3: Process tasks ready for execution
  process-tasks:
    name: Execute Tasks
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'issues' || github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git operations

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install automation
        run: pip install -e .

      - name: Execute tasks
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          automation process-all --tag execute

  # Job 4: Review pull requests
  code-review:
    name: Code Review
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install automation
        run: pip install -e .

      - name: Review PRs
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          automation process-all --tag needs-review

  # Job 5: QA - Build and Test
  qa-check:
    name: QA Build & Test
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js (for projects that need it)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install automation
        run: pip install -e .

      - name: Run QA
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          automation process-all --tag requires-qa

  # Job 6: Health monitoring
  health-check:
    name: System Health Check
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install automation
        run: pip install -e .

      - name: Run health check
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          automation health-check || echo "Health check completed with warnings"

      - name: List active plans
        run: |
          automation list-plans

  # Job 7: Docker build and publish (optional)
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: |
            gitea-automation:latest
            gitea-automation:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run --rm gitea-automation:latest --help

  # Summary job
  summary:
    name: Workflow Summary
    runs-on: ubuntu-latest
    needs: [build, process-planning, process-tasks, code-review, qa-check, health-check]
    if: always()

    steps:
      - name: Generate summary
        run: |
          echo "## Automation Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Planning | ${{ needs.process-planning.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Tasks | ${{ needs.process-tasks.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Review | ${{ needs.code-review.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| QA | ${{ needs.qa-check.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Health Check | ${{ needs.health-check.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** ${{ gitea.repository }}" >> $GITHUB_STEP_SUMMARY
