name: Sapiens Monitor

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -e .

      - name: Generate health report
        env:
          GITEA_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
        run: |
          sapiens health-check > health-report.md

      - name: Check for failures
        run: |
          sapiens check-failures --since-hours 24

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: health-report
          path: health-report.md
