name: Needs Planning

# Triggers specifically when 'needs-planning' label is added
on:
  issues:
    types: [labeled]

jobs:
  create-plan:
    name: Create Development Plan
    if: gitea.event.label.name == 'needs-planning'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Download pre-built wheel (if available)
        uses: actions/download-artifact@v3
        with:
          name: automation-wheel
          path: dist/
        continue-on-error: true

      - name: Install automation
        run: |
          pip install --upgrade pip
          # Use pre-built wheel if available, otherwise install from source
          if [ -f dist/*.whl ]; then
            echo "✅ Using pre-built wheel"
            pip install dist/*.whl
          else
            echo "⚠️ Building from source"
            pip install -e .
          fi

      - name: Create plan proposal
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          echo "🔍 Processing issue #${{ gitea.event.issue.number }} for planning"
          automation process-issue --issue ${{ gitea.event.issue.number }}

      - name: Comment on success
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITEA_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Plan proposal created!**\n\nThe development plan has been generated. Review the plan and add the `approved` label to proceed with task creation.\n\n🤖 Posted by Builder Automation'
            })

      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITEA_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Plan creation failed**\n\nThere was an error creating the development plan. Check the workflow logs for details.\n\n🤖 Posted by Builder Automation'
            })
