name: Code Review

# Triggers when 'needs-review' label is added
on:
  issues:
    types: [labeled]

jobs:
  code-review:
    name: Automated Code Review
    if: gitea.event.label.name == 'needs-review'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILDER_GITEA_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install automation
        run: pip install -e .

      - name: Run code review
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ secrets.BUILDER_GITEA_URL }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ gitea.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ gitea.repository }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.BUILDER_CLAUDE_API_KEY }}
        run: |
          echo "🔍 Running code review for issue/PR #${{ gitea.event.issue.number }}"
          sapiens process-issue --issue ${{ gitea.event.issue.number }}

      - name: Upload review artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: review-artifacts-${{ gitea.event.issue.number }}
          path: .automation/reviews/
          retention-days: 30
