name: Plan Merged - Generate Prompts

on:
  push:
    branches:
      - main
    paths:
      - 'plans/**/*.md'

jobs:
  generate-prompts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit to detect changes

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -e .

      - name: Detect changed plans
        id: detect-plans
        run: |
          # Get list of changed plan files
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '^plans/.*\.md$' || true)

          if [ -z "$CHANGED_FILES" ]; then
            echo "No plan files changed"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changed plans:"
            echo "$CHANGED_FILES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "plan_files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Generate prompts from plans
        if: steps.detect-plans.outputs.has_changes == 'true'
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.GITEA_TOKEN }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          # Process each changed plan file
          echo "${{ steps.detect-plans.outputs.plan_files }}" | while read -r plan_file; do
            if [ -n "$plan_file" ]; then
              echo "Processing plan: $plan_file"

              # Extract plan ID from filename (e.g., plans/42-feature.md -> 42)
              plan_id=$(basename "$plan_file" | sed 's/^\([0-9]*\)-.*/\1/')

              automation generate-prompts \
                --plan-file "$plan_file" \
                --plan-id "$plan_id"
            fi
          done

      - name: Report results
        if: always()
        run: |
          echo "Prompt generation completed"
          automation list-active-plans
