name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"

      - name: Run linters
        run: |
          black --check repo_sapiens/ tests/ || true
          ruff check repo_sapiens/ tests/ || true

      - name: Run type checker
        run: |
          mypy repo_sapiens/ || true

      - name: Run tests
        run: |
          pytest tests/ -v --cov=repo_sapiens --cov-report=xml --cov-report=html || true

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
