# @repo-sapiens-template
# @version: 1.0.0
# @name: sapiens-task
#
# Sapiens AI Task - GitLab CI/CD Include Template
#
# A reusable CI/CD template for running AI tasks with repo-sapiens.
# Unlike GitHub/Gitea composite actions, GitLab uses `include:` with templates.
#
# Usage in your .gitlab-ci.yml:
#
#   include:
#     - local: 'templates/actions/gitlab/sapiens-task/action.yaml'
#       # Or from a remote URL:
#       # - remote: 'https://example.com/sapiens-task/action.yaml'
#
#   my-ai-task:
#     extends: .sapiens-task
#     variables:
#       SAPIENS_TASK: "Analyze the codebase and suggest improvements"
#       SAPIENS_CONFIG: ".sapiens/config.yaml"  # optional
#       SAPIENS_TIMEOUT: "300"                   # optional
#
# Required CI/CD Variables (set in project settings):
#   - GITLAB_TOKEN: GitLab API token
#   - ANTHROPIC_API_KEY or OPENAI_API_KEY: AI provider credentials
#
# Optional Variables (can be set per-job):
#   - SAPIENS_TASK: The task prompt (required per-job)
#   - SAPIENS_CONFIG: Config file path (default: .sapiens/config.yaml)
#   - SAPIENS_TIMEOUT: Max execution time in seconds (default: 300)
#   - SAPIENS_PYTHON_VERSION: Python version (default: 3.12)
#   - SAPIENS_WORKING_DIR: Working directory (default: .)

variables:
  SAPIENS_CONFIG: ".sapiens/config.yaml"
  SAPIENS_TIMEOUT: "300"
  SAPIENS_PYTHON_VERSION: "3.12"
  SAPIENS_WORKING_DIR: "."

# Base template for sapiens tasks
.sapiens-task:
  image: python:${SAPIENS_PYTHON_VERSION}
  variables:
    # Git provider credentials
    GITLAB_TOKEN: $GITLAB_TOKEN
    AUTOMATION__GIT_PROVIDER__API_TOKEN: $GITLAB_TOKEN
    # Agent provider credentials (set in CI/CD variables)
    ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY
    OPENAI_API_KEY: $OPENAI_API_KEY
    # Use whichever API key is available
    AUTOMATION__AGENT_PROVIDER__API_KEY: $ANTHROPIC_API_KEY
  before_script:
    - pip install --quiet repo-sapiens
    - |
      # Validate configuration
      cd "${SAPIENS_WORKING_DIR}"
      if [ ! -f "${SAPIENS_CONFIG}" ]; then
        echo "ERROR: Configuration file not found: ${SAPIENS_CONFIG}"
        echo "Run 'sapiens init' to create the configuration."
        exit 1
      fi
  script:
    - |
      cd "${SAPIENS_WORKING_DIR}"

      if [ -z "${SAPIENS_TASK}" ]; then
        echo "ERROR: SAPIENS_TASK variable is required"
        exit 1
      fi

      echo "Running AI task: ${SAPIENS_TASK}"

      # Run the task and capture exit code
      set +e
      sapiens --config "${SAPIENS_CONFIG}" run "${SAPIENS_TASK}" --timeout "${SAPIENS_TIMEOUT}"
      EXIT_CODE=$?
      set -e

      # Create output file for downstream jobs
      echo "SAPIENS_EXIT_CODE=${EXIT_CODE}" >> sapiens_output.env
      if [ $EXIT_CODE -eq 0 ]; then
        echo "SAPIENS_SUCCESS=true" >> sapiens_output.env
      else
        echo "SAPIENS_SUCCESS=false" >> sapiens_output.env
      fi

      exit $EXIT_CODE
  artifacts:
    reports:
      dotenv: sapiens_output.env
    paths:
      - sapiens_output.env
    when: always
    expire_in: 1 day

# Example: Quick task with short timeout
.sapiens-task-quick:
  extends: .sapiens-task
  variables:
    SAPIENS_TIMEOUT: "60"

# Example: Long-running task with extended timeout
.sapiens-task-long:
  extends: .sapiens-task
  variables:
    SAPIENS_TIMEOUT: "900"
