# Sapiens Automation Daemon for Gitea Actions
#
# This workflow runs repo-sapiens periodically to process issues automatically
# using a local Ollama instance for AI processing.
#
# Required secrets:
#   - BUILDER_GITEA_TOKEN: Gitea API token with repo/issue access

name: Sapiens Daemon

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger

env:
  CONFIG_FILE: sapiens_config.ci.yaml

jobs:
  process-pending:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Verify installation
        run: |
          uv run sapiens --version || echo "Version check failed, continuing..."
          uv run sapiens --help

      - name: Process all pending issues
        env:
          # Git provider credentials
          GITEA_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          GITEA_API_TOKEN: ${{ secrets.BUILDER_GITEA_TOKEN }}
          # Gitea server URL (for API calls)
          GITEA_URL: ${{ gitea.server_url }}
        run: |
          echo "Using config: $CONFIG_FILE"
          echo "Server URL: $GITEA_URL"
          uv run sapiens --config "$CONFIG_FILE" --log-level DEBUG process-all

      - name: Upload state artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: workflow-state-${{ gitea.run_number }}
          path: .sapiens/state/
          retention-days: 7
          if-no-files-found: ignore
