# @repo-sapiens-template
# @version: 1.0.0
# @name: automation-daemon
#
# Sapiens Automation Daemon for GitLab CI/CD
#
# This pipeline runs repo-sapiens periodically to process issues automatically.
#
# Setup:
# 1. Copy this file to .gitlab-ci.yml (or include it via `include:`)
# 2. Set required CI/CD variables in your project settings:
#    - GITLAB_TOKEN: Your GitLab API token (or use CI_JOB_TOKEN for limited access)
#    - OPENAI_API_KEY: (if using Goose with OpenAI)
#    - ANTHROPIC_API_KEY or CLAUDE_API_KEY: (if using Claude)
# 3. Set up a pipeline schedule in CI/CD > Schedules (e.g., every 5 minutes)
# 4. Update CONFIG_FILE to match your config
#
# Note: GitLab scheduled pipelines are configured via the UI, not cron in YAML.
# Go to: Settings > CI/CD > Pipeline schedules > New schedule

variables:
  # Change this to your config file (use sapiens_config.ci.yaml for CI/CD specific config)
  CONFIG_FILE: sapiens_config.yaml
  PYTHON_VERSION: "3.11"

stages:
  - process

# Default settings for all jobs
default:
  interruptible: true

# Process all pending issues
process-pending:
  stage: process
  image: python:${PYTHON_VERSION}-slim
  timeout: 30 minutes
  rules:
    # Run on schedule (configured via GitLab UI)
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Allow manual trigger from pipeline UI
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    # Allow API trigger
    - if: $CI_PIPELINE_SOURCE == "api"
  variables:
    # Git provider credentials - use CI_JOB_TOKEN for limited access or set GITLAB_TOKEN
    GITLAB_TOKEN: $GITLAB_TOKEN
    # Prevent pip from caching (reduces image size)
    PIP_NO_CACHE_DIR: "1"
    # AI provider credentials (set in CI/CD variables as masked/protected)
    # OPENAI_API_KEY: $OPENAI_API_KEY
    # ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY
    # CLAUDE_API_KEY: $CLAUDE_API_KEY
  before_script:
    - pip install --quiet --no-cache-dir repo-sapiens
    # If using Goose, also install it:
    # - pip install --no-cache-dir goose-ai
  script:
    - sapiens --config $CONFIG_FILE process-all --log-level INFO
  artifacts:
    paths:
      - .automation/state/
    expire_in: 7 days
    when: always
  # Resource optimization
  resource_group: sapiens-daemon
