# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Use requirements from docs/requirements.txt for building
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Optional: declare the programming language(s) used in your project
# language: python

# Build PDF and ePub
formats:
  - html
  - pdf
  - epub
