# @version: 1.0.0
# Sapiens AI Task - Gitea Composite Action
# Reusable action for running AI tasks with repo-sapiens

name: 'Sapiens AI Task'
description: 'Run an AI task using the configured agent from .sapiens/config.yaml'
author: 'repo-sapiens'

inputs:
  task:
    description: 'Task prompt for the AI agent'
    required: true
  config:
    description: 'Path to sapiens config file'
    required: false
    default: '.sapiens/config.yaml'
  working-directory:
    description: 'Working directory for execution'
    required: false
    default: '.'
  timeout:
    description: 'Max execution time in seconds'
    required: false
    default: '300'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  # Secrets - pass as inputs for composite action compatibility
  anthropic-api-key:
    description: 'Anthropic API key (for Claude API or builtin with Anthropic)'
    required: false
  openai-api-key:
    description: 'OpenAI API key (for builtin with OpenAI)'
    required: false
  gitea-token:
    description: 'Gitea API token'
    required: false

outputs:
  success:
    description: 'Whether the task completed successfully'
    value: ${{ steps.run-task.outputs.success }}
  exit-code:
    description: 'Exit code from sapiens run'
    value: ${{ steps.run-task.outputs.exit-code }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install repo-sapiens
      shell: bash
      run: pip install repo-sapiens

    - name: Validate configuration
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -f "${{ inputs.config }}" ]; then
          echo "::error::Configuration file not found: ${{ inputs.config }}"
          echo "Run 'sapiens init' to create the configuration."
          exit 1
        fi

    - name: Run AI task
      id: run-task
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        # Git provider credentials
        GITEA_TOKEN: ${{ inputs.gitea-token }}
        AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ inputs.gitea-token }}
        # Agent provider credentials (set whichever is provided)
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ inputs.anthropic-api-key || inputs.openai-api-key }}
      run: |
        set +e
        sapiens --config "${{ inputs.config }}" run "${{ inputs.task }}" --timeout ${{ inputs.timeout }}
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -eq 0 ]; then
          echo "success=true" >> $GITHUB_OUTPUT
        else
          echo "success=false" >> $GITHUB_OUTPUT
        fi
        echo "exit-code=$EXIT_CODE" >> $GITHUB_OUTPUT

        exit $EXIT_CODE
