# @repo-sapiens-template
# @version: 1.1.0
# @name: daily-issue-triage
#
# Daily Issue Triage for Gitea Actions
#
# Automatically reviews and labels new issues, adds initial assessments,
# and identifies issues that need immediate attention.
#
# Setup:
# 1. Copy to .gitea/workflows/daily-issue-triage.yaml
# 2. Set required secrets:
#    - SAPIENS_GITEA_TOKEN: Gitea API token with issue write access
#    - SAPIENS_OLLAMA_URL: Ollama base URL (e.g., http://192.168.1.241:11434)
# 3. Create labels: bug, enhancement, question, needs-triage, priority-high

name: Daily Issue Triage

on:
  schedule:
    # Every day at 8am UTC
    - cron: '0 8 * * *'
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  triage-issues:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install repo-sapiens
        env:
          SAPIENS_REPO_URL: ${{ secrets.SAPIENS_REPO_URL }}
          SAPIENS_BRANCH: ${{ secrets.SAPIENS_BRANCH }}
        run: |
          if [ -n "$SAPIENS_REPO_URL" ]; then
            echo "Installing from $SAPIENS_REPO_URL (branch: ${SAPIENS_BRANCH:-main})"
            git clone "$SAPIENS_REPO_URL" /tmp/repo-sapiens
            cd /tmp/repo-sapiens
            git checkout "${SAPIENS_BRANCH:-main}"
            pip install -e .
          else
            echo "Installing from PyPI"
            pip install repo-sapiens
          fi

      - name: Triage issues
        env:
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ github.server_url }}
          AUTOMATION__REPOSITORY__OWNER: ${{ github.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ github.event.repository.name }}
          # For ollama - pass base URL (no API key needed)
          AUTOMATION__AGENT_PROVIDER__BASE_URL: ${{ secrets.SAPIENS_OLLAMA_URL }}
        run: |
          sapiens task "Triage open issues in this repository.

          Repository: ${{ github.repository }}

          Tasks:
          1. Use the Gitea API to list open issues without labels (needs-triage or unlabeled)
          2. For each untriaged issue:
             a. Read the issue title and body
             b. Categorize: bug, enhancement, question, or documentation
             c. Assess priority: low, medium, high (based on impact and urgency)
             d. Add appropriate labels via API
             e. If high priority, add a comment noting it needs attention
          3. For issues older than 7 days without response, add 'stale' label

          Label mapping:
          - Bug reports → 'bug' label
          - Feature requests → 'enhancement' label
          - Questions → 'question' label
          - Security issues → 'priority-high' + 'security' labels

          Guidelines:
          - Be helpful and welcoming in any comments
          - Don't close issues automatically
          - Flag unclear issues for human review
          - Note if issue is a duplicate (but don't close)

          Gitea API base: ${{ github.server_url }}/api/v1
          Use token from AUTOMATION__GIT_PROVIDER__API_TOKEN for auth."
