# @repo-sapiens-template
# @version: 1.1.0
# @name: weekly-sbom-license
#
# Weekly SBOM Generation & License Compliance for Gitea Actions
#
# Generates Software Bill of Materials (SBOM), scans for vulnerabilities,
# checks license compliance, and creates issues for problems found.
#
# Tools Used:
#   - Syft (Anchore): SBOM generation
#   - Grype (Anchore): Vulnerability scanning against SBOM
#   - License analysis: Custom checks for copyleft/incompatible licenses
#
# Setup:
# 1. Copy to .gitea/workflows/weekly-sbom-license.yaml
# 2. Set required secrets:
#    - SAPIENS_GITEA_TOKEN: Gitea API token with repo write access
#    - SAPIENS_CLAUDE_API_KEY: Claude API key (optional, for AI analysis)
# 3. Configure PROJECT_LICENSE and DENY_LICENSES below
# 4. Adjust schedule as needed

name: Weekly SBOM & License Compliance

on:
  schedule:
    # Every Monday at 6am UTC (start of week)
    - cron: '0 6 * * 1'
  workflow_dispatch:
    inputs:
      create_issues:
        description: 'Create issues for problems found'
        required: false
        default: 'true'
      fail_on_vulnerabilities:
        description: 'Fail on high/critical vulnerabilities'
        required: false
        default: 'false'

env:
  GITEA_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
  # Your project's license (used to check compatibility)
  PROJECT_LICENSE: "{{PROJECT_LICENSE}}"
  # Licenses to deny (comma-separated, e.g., "GPL-3.0,AGPL-3.0")
  # Common restrictive licenses that may conflict with proprietary use
  DENY_LICENSES: "{{DENY_LICENSES}}"

jobs:
  sbom-and-license:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft (SBOM generator)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Grype (vulnerability scanner)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (CycloneDX format)
        run: |
          echo "Generating Software Bill of Materials..."
          syft dir:. -o cyclonedx-json=sbom.cyclonedx.json -o spdx-json=sbom.spdx.json -o json=sbom.syft.json

          echo "SBOM generated successfully"

          # Count components
          COMPONENT_COUNT=$(python3 -c "
          import json
          data = json.load(open('sbom.cyclonedx.json'))
          components = data.get('components', [])
          print(len(components))
          ")
          echo "Total components: $COMPONENT_COUNT"
          echo "COMPONENT_COUNT=$COMPONENT_COUNT" >> $GITHUB_ENV

      - name: Scan for vulnerabilities with Grype
        run: |
          echo "Scanning SBOM for known vulnerabilities..."
          grype sbom:sbom.cyclonedx.json -o json > grype-results.json 2>/dev/null || true

          # Parse results
          python3 << 'EOF'
          import json
          import os

          try:
              data = json.load(open('grype-results.json'))
              matches = data.get('matches', [])

              # Count by severity
              severity_counts = {'Critical': 0, 'High': 0, 'Medium': 0, 'Low': 0, 'Negligible': 0}
              for m in matches:
                  vuln = m.get('vulnerability', {})
                  sev = vuln.get('severity', 'Unknown')
                  if sev in severity_counts:
                      severity_counts[sev] += 1

              print(f"Vulnerabilities found: {len(matches)}")
              for sev, count in severity_counts.items():
                  if count > 0:
                      print(f"  {sev}: {count}")

              # Set environment variables
              with open(os.environ['GITHUB_ENV'], 'a') as f:
                  f.write(f"VULN_TOTAL={len(matches)}\n")
                  f.write(f"VULN_CRITICAL={severity_counts['Critical']}\n")
                  f.write(f"VULN_HIGH={severity_counts['High']}\n")

          except Exception as e:
              print(f"Error parsing Grype results: {e}")
              with open(os.environ['GITHUB_ENV'], 'a') as f:
                  f.write("VULN_TOTAL=0\n")
                  f.write("VULN_CRITICAL=0\n")
                  f.write("VULN_HIGH=0\n")
          EOF

      - name: Analyze licenses
        run: |
          echo "Analyzing component licenses..."

          python3 << 'EOF'
          import json
          import os
          import re

          # Load SBOM
          data = json.load(open('sbom.cyclonedx.json'))
          components = data.get('components', [])

          # Parse denied licenses from env
          deny_licenses_raw = os.environ.get('DENY_LICENSES', '')
          deny_licenses = [l.strip().lower() for l in deny_licenses_raw.split(',') if l.strip()]

          # Common copyleft licenses (restrictive for proprietary use)
          COPYLEFT_LICENSES = [
              'gpl', 'agpl', 'lgpl', 'cc-by-sa', 'mpl', 'cddl', 'epl',
              'osl', 'eupl', 'cecill'
          ]

          # Permissive licenses (generally safe)
          PERMISSIVE_LICENSES = [
              'mit', 'apache', 'bsd', 'isc', 'unlicense', 'cc0', 'wtfpl',
              'zlib', 'boost', 'public domain', '0bsd'
          ]

          license_summary = {
              'permissive': [],
              'copyleft': [],
              'denied': [],
              'unknown': []
          }

          problems = []

          for comp in components:
              name = comp.get('name', 'unknown')
              version = comp.get('version', '?')
              licenses = comp.get('licenses', [])

              if not licenses:
                  license_summary['unknown'].append(f"{name}@{version}")
                  continue

              for lic in licenses:
                  # Handle different license formats in CycloneDX
                  if isinstance(lic, dict):
                      lic_id = lic.get('license', {}).get('id', '') or lic.get('license', {}).get('name', '')
                      lic_expression = lic.get('expression', '')
                      lic_str = lic_id or lic_expression
                  else:
                      lic_str = str(lic)

                  lic_lower = lic_str.lower()

                  # Check if denied
                  if any(d in lic_lower for d in deny_licenses):
                      license_summary['denied'].append(f"{name}@{version} ({lic_str})")
                      problems.append({
                          'type': 'denied_license',
                          'component': name,
                          'version': version,
                          'license': lic_str
                      })
                  # Check if copyleft
                  elif any(c in lic_lower for c in COPYLEFT_LICENSES):
                      license_summary['copyleft'].append(f"{name}@{version} ({lic_str})")
                      # Only flag as problem if not explicitly allowed
                      if 'lgpl' not in lic_lower:  # LGPL is often acceptable
                          problems.append({
                              'type': 'copyleft_license',
                              'component': name,
                              'version': version,
                              'license': lic_str
                          })
                  # Check if permissive
                  elif any(p in lic_lower for p in PERMISSIVE_LICENSES):
                      license_summary['permissive'].append(f"{name}@{version}")
                  else:
                      license_summary['unknown'].append(f"{name}@{version} ({lic_str})")

          # Print summary
          print("License Summary:")
          print(f"  Permissive: {len(license_summary['permissive'])}")
          print(f"  Copyleft: {len(license_summary['copyleft'])}")
          print(f"  Denied: {len(license_summary['denied'])}")
          print(f"  Unknown: {len(license_summary['unknown'])}")

          # Save results
          with open('license-analysis.json', 'w') as f:
              json.dump({
                  'summary': {k: len(v) for k, v in license_summary.items()},
                  'details': license_summary,
                  'problems': problems
              }, f, indent=2)

          # Set env vars
          with open(os.environ['GITHUB_ENV'], 'a') as f:
              f.write(f"LICENSE_PROBLEMS={len(problems)}\n")
              f.write(f"LICENSE_DENIED={len(license_summary['denied'])}\n")
              f.write(f"LICENSE_COPYLEFT={len(license_summary['copyleft'])}\n")
              f.write(f"LICENSE_UNKNOWN={len(license_summary['unknown'])}\n")

          EOF

      - name: Compare with previous SBOM
        continue-on-error: true
        run: |
          # Try to fetch previous SBOM from artifacts or releases
          echo "Checking for SBOM changes..."

          # For now, just note this is the baseline
          # Future: compare with stored SBOM to detect new deps, removed deps, version changes
          echo "SBOM_DIFF=baseline" >> $GITHUB_ENV

      - name: Generate comprehensive report
        run: |
          python3 << 'EOF'
          import json
          import os
          from datetime import datetime

          # Load all data
          sbom = json.load(open('sbom.cyclonedx.json'))
          grype = json.load(open('grype-results.json')) if os.path.exists('grype-results.json') else {'matches': []}
          licenses = json.load(open('license-analysis.json'))

          components = sbom.get('components', [])
          vulnerabilities = grype.get('matches', [])

          report = []
          report.append("# SBOM & License Compliance Report")
          report.append(f"\nGenerated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
          report.append(f"Repository: {os.environ.get('GITHUB_REPOSITORY', 'unknown')}")
          report.append("")

          # Summary table
          report.append("## Summary")
          report.append("")
          report.append("| Metric | Count |")
          report.append("|--------|-------|")
          report.append(f"| Total Components | {len(components)} |")
          report.append(f"| Vulnerabilities | {len(vulnerabilities)} |")
          report.append(f"| Critical/High CVEs | {os.environ.get('VULN_CRITICAL', 0)}/{os.environ.get('VULN_HIGH', 0)} |")
          report.append(f"| License Issues | {licenses['summary'].get('denied', 0) + licenses['summary'].get('copyleft', 0)} |")
          report.append(f"| Unknown Licenses | {licenses['summary'].get('unknown', 0)} |")
          report.append("")

          # Vulnerabilities section
          if vulnerabilities:
              report.append("## Vulnerabilities")
              report.append("")

              # Group by severity
              by_severity = {}
              for v in vulnerabilities:
                  sev = v.get('vulnerability', {}).get('severity', 'Unknown')
                  if sev not in by_severity:
                      by_severity[sev] = []
                  by_severity[sev].append(v)

              for sev in ['Critical', 'High', 'Medium', 'Low']:
                  if sev in by_severity:
                      report.append(f"### {sev} ({len(by_severity[sev])})")
                      report.append("")
                      report.append("| Package | Version | CVE | Fix Available |")
                      report.append("|---------|---------|-----|---------------|")

                      for v in by_severity[sev][:10]:  # Limit to 10 per severity
                          vuln = v.get('vulnerability', {})
                          artifact = v.get('artifact', {})
                          pkg = artifact.get('name', 'unknown')
                          ver = artifact.get('version', '?')
                          cve = vuln.get('id', 'N/A')
                          fix = vuln.get('fix', {}).get('versions', [])
                          fix_str = fix[0] if fix else 'No'

                          report.append(f"| {pkg} | {ver} | {cve} | {fix_str} |")

                      if len(by_severity[sev]) > 10:
                          report.append(f"\n*... and {len(by_severity[sev]) - 10} more {sev.lower()} vulnerabilities*")
                      report.append("")

          # License issues section
          if licenses['problems']:
              report.append("## License Issues")
              report.append("")

              denied = [p for p in licenses['problems'] if p['type'] == 'denied_license']
              copyleft = [p for p in licenses['problems'] if p['type'] == 'copyleft_license']

              if denied:
                  report.append("### Denied Licenses")
                  report.append("")
                  report.append("These components use licenses that are explicitly denied:")
                  report.append("")
                  for p in denied[:10]:
                      report.append(f"- **{p['component']}@{p['version']}**: {p['license']}")
                  report.append("")

              if copyleft:
                  report.append("### Copyleft Licenses (Review Required)")
                  report.append("")
                  report.append("These components use copyleft licenses that may have restrictions:")
                  report.append("")
                  for p in copyleft[:10]:
                      report.append(f"- **{p['component']}@{p['version']}**: {p['license']}")
                  report.append("")

          # Unknown licenses
          if licenses['details'].get('unknown'):
              report.append("## Unknown Licenses")
              report.append("")
              report.append("These components have unrecognized or missing license information:")
              report.append("")
              for comp in licenses['details']['unknown'][:15]:
                  report.append(f"- {comp}")
              if len(licenses['details']['unknown']) > 15:
                  report.append(f"\n*... and {len(licenses['details']['unknown']) - 15} more*")
              report.append("")

          # Top dependencies
          report.append("## Top Dependencies by Type")
          report.append("")

          # Group by type
          by_type = {}
          for c in components:
              ctype = c.get('type', 'unknown')
              if ctype not in by_type:
                  by_type[ctype] = []
              by_type[ctype].append(c)

          for ctype, comps in sorted(by_type.items(), key=lambda x: -len(x[1]))[:5]:
              report.append(f"- **{ctype}**: {len(comps)} components")
          report.append("")

          # Write report
          with open('sbom-report.md', 'w') as f:
              f.write('\n'.join(report))

          print("Report generated: sbom-report.md")
          EOF

      - name: AI Analysis (optional)
        if: env.VULN_TOTAL != '0' || env.LICENSE_PROBLEMS != '0'
        continue-on-error: true
        env:
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.SAPIENS_CLAUDE_API_KEY }}
        run: |
          if [ -z "$AUTOMATION__AGENT_PROVIDER__API_KEY" ]; then
            echo "No API key configured, skipping AI analysis"
            exit 0
          fi

          pip install repo-sapiens || pip3 install repo-sapiens

          sapiens task "Analyze this SBOM and security report for a software project.

          $(cat sbom-report.md)

          License Analysis Details:
          $(cat license-analysis.json)

          Tasks:
          1. Prioritize the vulnerabilities by actual risk (considering exploitability, not just severity)
          2. For license issues, explain the specific compliance risks
          3. Recommend which dependencies should be updated or replaced
          4. Identify any patterns (e.g., outdated ecosystem, too many transitive deps)
          5. Write a concise executive summary (3-5 bullet points) for the maintainers

          Output your analysis to 'ai-analysis.md' using the write_file tool.

          Be practical - focus on actionable recommendations, not theoretical risks."

      - name: Create issue for critical findings
        if: (env.VULN_CRITICAL != '0' || env.VULN_HIGH != '0' || env.LICENSE_DENIED != '0') && (github.event.inputs.create_issues != 'false')
        run: |
          # Prepare issue body
          ISSUE_BODY=$(cat << 'ISSUE_EOF'
          ## SBOM & License Compliance Alert

          The weekly SBOM scan has identified issues requiring attention.

          ### Summary
          - **Critical Vulnerabilities**: ${{ env.VULN_CRITICAL }}
          - **High Vulnerabilities**: ${{ env.VULN_HIGH }}
          - **Denied Licenses**: ${{ env.LICENSE_DENIED }}
          - **Total Components**: ${{ env.COMPONENT_COUNT }}

          ### Full Report
          See the workflow artifacts for:
          - `sbom-report.md` - Full analysis report
          - `sbom.cyclonedx.json` - SBOM in CycloneDX format
          - `sbom.spdx.json` - SBOM in SPDX format
          - `grype-results.json` - Vulnerability scan results
          - `license-analysis.json` - License compliance details

          ### Recommended Actions
          1. Review critical and high vulnerabilities for exploitability
          2. Update affected dependencies to patched versions
          3. Review license conflicts for compliance requirements
          4. Consider replacing components with denied licenses

          ---
          *Generated by repo-sapiens weekly SBOM workflow*
          ISSUE_EOF
          )

          # Create issue via API
          curl -X POST \
            -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/issues" \
            -d "{
              \"title\": \"SBOM Alert: $(date +%Y-%m-%d) - ${{ env.VULN_CRITICAL }} critical, ${{ env.LICENSE_DENIED }} license issues\",
              \"body\": $(echo "$ISSUE_BODY" | jq -Rs .),
              \"labels\": [\"security\", \"dependencies\", \"automated\"]
            }" || echo "Issue creation failed"

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.run_number }}
          path: |
            sbom.cyclonedx.json
            sbom.spdx.json
            sbom.syft.json
            grype-results.json
            license-analysis.json
            sbom-report.md
            ai-analysis.md
          retention-days: 90

      - name: Commit SBOM to repository (optional)
        if: always()
        continue-on-error: true
        run: |
          # Optionally commit SBOM to repo for tracking
          mkdir -p .sbom
          cp sbom.cyclonedx.json .sbom/
          cp sbom.spdx.json .sbom/

          git config user.name "repo-sapiens[bot]"
          git config user.email "repo-sapiens[bot]@users.noreply.github.com"

          git add .sbom/
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update SBOM $(date +%Y-%m-%d)

          Components: ${{ env.COMPONENT_COUNT }}
          Vulnerabilities: ${{ env.VULN_TOTAL }}

          [skip ci]"
            git push || echo "Push failed - may need write permissions"
          fi

      - name: Fail on critical vulnerabilities
        if: github.event.inputs.fail_on_vulnerabilities == 'true'
        run: |
          if [ "${{ env.VULN_CRITICAL }}" != "0" ] || [ "${{ env.VULN_HIGH }}" != "0" ]; then
            echo "Critical or high vulnerabilities found!"
            echo "Critical: ${{ env.VULN_CRITICAL }}"
            echo "High: ${{ env.VULN_HIGH }}"
            exit 1
          fi
