# @repo-sapiens-template
# @version: 2.0.1
# @name: post-merge-docs
# @type: thin-wrapper
#
# Post-Merge Documentation Update - Thin Wrapper
#
# Calls the reusable workflow from savorywatt/repo-sapiens.
# Automatically reviews changes after merges and updates documentation.
#
# Setup:
# 1. Copy to .github/workflows/post-merge-docs.yaml
# 2. Set required secrets:
#    - SAPIENS_GITHUB_TOKEN: GitHub token with repo access
#    - ANTHROPIC_API_KEY: Claude API key
# 3. Configure docs_path if your docs are not in 'docs/'

name: Update Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Required for cross-repo reusable workflow
permissions:
  contents: write

jobs:
  post-merge-docs:
    uses: savorywatt/repo-sapiens/.github/workflows/sapiens-post-merge-docs.yaml@v2
    with:
      docs_path: docs
      auto_commit: true
    secrets:
      GIT_TOKEN: ${{ secrets.SAPIENS_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      AI_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
