# @repo-sapiens-template
# @version: 2.0.1
# @name: weekly-test-coverage
# @type: thin-wrapper
#
# Weekly Test Coverage Improvement - Thin Wrapper
#
# Calls the reusable workflow from savorywatt/repo-sapiens.
# Analyzes test coverage and creates PRs with new tests.
#
# Setup:
# 1. Copy to .github/workflows/weekly-test-coverage.yaml
# 2. Set required secrets:
#    - SAPIENS_GITHUB_TOKEN: GitHub token with repo access
#    - ANTHROPIC_API_KEY: Claude API key
# 3. Configure coverage_threshold as needed
# 4. Adjust schedule as needed

name: Improve Test Coverage

on:
  schedule:
    # Every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Manual trigger - uses default coverage threshold from reusable workflow (60%)

# Required for cross-repo reusable workflow
permissions:
  contents: write
  pull-requests: write

jobs:
  test-coverage:
    uses: savorywatt/repo-sapiens/.github/workflows/sapiens-test-coverage.yaml@v2
    # All inputs use defaults from the reusable workflow
    # Customize test_command if needed: "python -m pytest tests/ --cov --cov-report=json"
    secrets:
      GIT_TOKEN: ${{ secrets.SAPIENS_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      AI_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
