# @repo-sapiens-template
# @version: 2.0.0
# @name: weekly-test-coverage
# @type: thin-wrapper
#
# Weekly Test Coverage Improvement - Thin Wrapper
#
# Calls the reusable workflow from savorywatt/repo-sapiens.
# Analyzes test coverage and creates PRs with new tests.
#
# Setup:
# 1. Copy to .github/workflows/weekly-test-coverage.yaml
# 2. Set required secrets:
#    - SAPIENS_GITHUB_TOKEN: GitHub token with repo access
#    - ANTHROPIC_API_KEY: Claude API key
# 3. Configure coverage_threshold as needed
# 4. Adjust schedule as needed

name: Improve Test Coverage

on:
  schedule:
    # Every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      target_coverage:
        description: 'Minimum coverage % to target'
        type: number
        default: 60

# Required for cross-repo reusable workflow
permissions:
  contents: write
  pull-requests: write

jobs:
  test-coverage:
    uses: savorywatt/repo-sapiens/.github/workflows/sapiens-test-coverage.yaml@v2
    with:
      # Convert to number using fromJSON to ensure proper type for reusable workflow
      coverage_threshold: ${{ fromJSON(github.event.inputs.target_coverage || '60') }}
      # Customize test command if needed (default: pytest with coverage)
      # test_command: "python -m pytest tests/ --cov --cov-report=json --cov-report=term -q"
    secrets:
      GIT_TOKEN: ${{ secrets.SAPIENS_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      AI_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
