# @repo-sapiens-template
# @version: 2.0.0
# @name: weekly-security-review
# @type: thin-wrapper
#
# Weekly Security Review - Thin Wrapper
#
# Calls the reusable workflow from savorywatt/repo-sapiens.
# Configure the 'languages' input for your project's tech stack.
#
# Setup:
# 1. Copy to .github/workflows/weekly-security-review.yaml
# 2. Set required secrets:
#    - SAPIENS_GITHUB_TOKEN: GitHub token with repo access
#    - ANTHROPIC_API_KEY: Claude API key (optional, for auto-fix)
# 3. Configure 'languages' below with your project's languages
# 4. Adjust schedule as needed

name: Weekly Security Review

on:
  schedule:
    # Every Friday at 2pm UTC (before weekend, gives time to review)
    - cron: '0 14 * * 5'
  workflow_dispatch:
    inputs:
      auto_fix:
        description: 'Automatically fix vulnerabilities'
        type: boolean
        default: true

# Required for cross-repo reusable workflow
permissions:
  contents: write
  pull-requests: write
  issues: write
  security-events: write

jobs:
  security-review:
    uses: savorywatt/repo-sapiens/.github/workflows/sapiens-security-review.yaml@v2
    with:
      # Configure which languages to scan (space-separated)
      # Options: python go java cpp csharp kotlin clojure rust typescript javascript
      languages: "{{SECURITY_LANGUAGES}}"
      auto_fix: ${{ github.event.inputs.auto_fix == 'true' || github.event.inputs.auto_fix == '' }}
      severity_threshold: medium
    secrets:
      GIT_TOKEN: ${{ secrets.SAPIENS_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      AI_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
