# @repo-sapiens-template
# @version: 1.0.0
# @name: daily-issue-triage
#
# Daily Issue Triage for GitLab CI/CD
#
# Automatically reviews and labels new issues, adds initial assessments,
# and identifies issues that need immediate attention.
#
# Setup:
# 1. Copy to .gitlab-ci.yml (or include via `include:`)
# 2. Set required CI/CD variables (Settings > CI/CD > Variables):
#    - SAPIENS_GITLAB_TOKEN: GitLab API token with issue write access (note: GITLAB_ prefix is reserved)
#    - SAPIENS_AI_API_KEY: Claude API key (masked, protected)
# 3. Create labels: bug, enhancement, question, needs-triage, priority-high
# 4. Set up a daily pipeline schedule (CI/CD > Schedules)
#
# Note: GitLab doesn't have native issue event triggers like GitHub/Gitea.
# This job runs on a schedule to scan for untriaged issues.

variables:
  PYTHON_VERSION: "3.11"
  PIP_NO_CACHE_DIR: "1"

stages:
  - triage

default:
  interruptible: true

triage-issues:
  stage: triage
  image: python:${PYTHON_VERSION}-slim
  timeout: 15 minutes
  rules:
    # Run on schedule (configure daily in GitLab UI)
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Allow manual trigger
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  variables:
    # Note: GITLAB_ prefix is reserved, so we source from SAPIENS_GITLAB_TOKEN
    GITLAB_TOKEN: $SAPIENS_GITLAB_TOKEN
    AUTOMATION__AGENT_PROVIDER__API_KEY: $SAPIENS_AI_API_KEY
  before_script:
    - pip install --quiet --no-cache-dir repo-sapiens
    - apt-get update && apt-get install -y curl jq
  script:
    - |
      echo "Fetching untriaged issues..."

      # Get issues without standard labels (bug, enhancement, question)
      ISSUES=$(curl --silent \
        --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/issues?state=opened&per_page=50" \
        | jq '[.[] | select(.labels | length == 0 or (all(. != "bug" and . != "enhancement" and . != "question")))]')

      ISSUE_COUNT=$(echo "$ISSUES" | jq 'length')
      echo "Found $ISSUE_COUNT untriaged issues"

      if [ "$ISSUE_COUNT" = "0" ]; then
        echo "No untriaged issues found"
        exit 0
      fi

      # Save issues for sapiens to process
      echo "$ISSUES" > untriaged_issues.json

      sapiens task "Triage open issues in this GitLab project.

      Project: ${CI_PROJECT_PATH}
      Untriaged issues: $(cat untriaged_issues.json)

      Tasks:
      1. For each issue in the list:
         a. Analyze the title and description
         b. Categorize: bug, enhancement, question, or documentation
         c. Assess priority: low, medium, high (based on impact and urgency)
         d. Add appropriate labels via GitLab API
         e. If high priority or security-related, add a comment noting it needs attention

      GitLab API examples:
      - Add label: curl -X PUT --header 'PRIVATE-TOKEN: \$GITLAB_TOKEN' '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/issues/<iid>?add_labels=bug'
      - Add comment: curl -X POST --header 'PRIVATE-TOKEN: \$GITLAB_TOKEN' --data 'body=message' '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/issues/<iid>/notes'

      Label mapping:
      - Bug reports -> 'bug' label
      - Feature requests -> 'enhancement' label
      - Questions -> 'question' label
      - Security issues -> 'priority-high' + 'security' labels

      Guidelines:
      - Be helpful and welcoming in any comments
      - Don't close issues automatically
      - Flag unclear issues with 'needs-info' label
      - Note if issue appears to be a duplicate"
  artifacts:
    paths:
      - untriaged_issues.json
    expire_in: 7 days
    when: always
