# @repo-sapiens-template
# @version: 1.0.0
# @name: post-merge-docs
#
# Post-Merge Documentation Update for GitLab CI/CD
#
# Automatically reviews changes after merges to main and updates
# documentation if needed (README, CHANGELOG, API docs).
#
# Setup:
# 1. Copy to .gitlab-ci.yml (or include via `include:`)
# 2. Set required CI/CD variables (Settings > CI/CD > Variables):
#    - SAPIENS_GITLAB_TOKEN: GitLab API token with repo write access (note: GITLAB_ prefix is reserved)
#    - SAPIENS_AI_API_KEY: Claude API key (masked, protected)
# 3. Customize the task prompt as needed

variables:
  PYTHON_VERSION: "3.12"
  PIP_NO_CACHE_DIR: "1"

stages:
  - update-docs

default:
  interruptible: true

update-docs:
  stage: update-docs
  image: python:${PYTHON_VERSION}-slim
  timeout: 15 minutes
  rules:
    # Run on pushes to default branch (main/master)
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      # Skip if commit message contains [skip docs] or [no docs]
      when: on_success
    # Allow manual trigger
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  variables:
    # Note: GITLAB_ prefix is reserved, so we source from SAPIENS_GITLAB_TOKEN
    GITLAB_TOKEN: $SAPIENS_GITLAB_TOKEN
    AUTOMATION__AGENT_PROVIDER__API_KEY: $SAPIENS_AI_API_KEY
  before_script:
    - pip install --quiet --no-cache-dir repo-sapiens
    - apt-get update && apt-get install -y git
    - git config user.name "gitlab-ci[bot]"
    - git config user.email "gitlab-ci[bot]@users.noreply.gitlab.com"
  script:
    - |
      # Skip if commit message contains skip markers
      if echo "$CI_COMMIT_MESSAGE" | grep -qE '\[(skip docs|no docs)\]'; then
        echo "Skipping documentation update (skip marker found)"
        exit 0
      fi

      # Get recent commits for context
      RECENT_COMMITS=$(git log --oneline -5)
      echo "Recent commits:"
      echo "$RECENT_COMMITS"

      sapiens task "Review the recent commits and update documentation if needed.

      Recent commits:
      $RECENT_COMMITS

      Tasks:
      1. Check if README.md needs updates for any new features or changed behavior
      2. Add CHANGELOG.md entries for notable changes (if not already present)
      3. Update any API documentation if function signatures changed
      4. Fix any broken links or outdated examples

      Only make changes if genuinely needed. If no updates required, just finish.
      If changes are made, commit them with message: 'docs: Update documentation [skip docs]'"

      # Push any changes
      git add -A
      if ! git diff --staged --quiet; then
        git commit -m "docs: Auto-update documentation [skip docs]"
        git push "https://gitlab-ci-token:${SAPIENS_GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:${CI_COMMIT_BRANCH} || echo "Push failed - may need write permissions"
      else
        echo "No documentation changes needed"
      fi
  allow_failure: true
