# @repo-sapiens-template
# @version: 1.1.0
# @name: weekly-sbom-license
#
# Weekly SBOM Generation & License Compliance for GitLab CI
#
# Generates Software Bill of Materials (SBOM), scans for vulnerabilities,
# checks license compliance, and creates issues for problems found.
#
# Tools Used:
#   - Syft (Anchore): SBOM generation
#   - Grype (Anchore): Vulnerability scanning against SBOM
#   - License analysis: Custom checks for copyleft/incompatible licenses
#
# Setup:
# 1. Copy to .gitlab-ci.yml (or include via `include:`)
# 2. Set required CI/CD variables:
#    - SAPIENS_GITLAB_TOKEN: GitLab API token
#    - SAPIENS_CLAUDE_API_KEY: Claude API key (optional, for AI analysis)
# 3. Configure PROJECT_LICENSE and DENY_LICENSES below
# 4. Create a pipeline schedule: Settings > CI/CD > Schedules (e.g., every Monday at 6am)

stages:
  - sbom

default:
  interruptible: true

variables:
  # Your project's license (used to check compatibility)
  PROJECT_LICENSE: "MIT"
  # Licenses to deny (comma-separated, e.g., "GPL-3.0,AGPL-3.0")
  DENY_LICENSES: ""
  PYTHON_VERSION: "3.12"

sbom-and-license:
  stage: sbom
  image: python:${PYTHON_VERSION}-slim
  timeout: 30 minutes
  rules:
    # Run on schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Allow manual trigger
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  variables:
    # Note: GITLAB_ prefix is reserved, so we source from SAPIENS_GITLAB_TOKEN
    GITLAB_TOKEN: $SAPIENS_GITLAB_TOKEN
    AUTOMATION__GIT_PROVIDER__BASE_URL: $CI_SERVER_URL
    AUTOMATION__GIT_PROVIDER__API_TOKEN: $SAPIENS_GITLAB_TOKEN
    AUTOMATION__REPOSITORY__OWNER: $CI_PROJECT_NAMESPACE
    AUTOMATION__REPOSITORY__NAME: $CI_PROJECT_NAME
    AUTOMATION__AGENT_PROVIDER__API_KEY: $SAPIENS_CLAUDE_API_KEY
  before_script:
    - apt-get update -qq && apt-get install -y -qq curl git
    # Install Syft (SBOM generator)
    - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    # Install Grype (vulnerability scanner)
    - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
  script:
    - |
      echo "Generating Software Bill of Materials..."
      syft dir:. -o cyclonedx-json=sbom.cyclonedx.json -o spdx-json=sbom.spdx.json -o json=sbom.syft.json

      echo "SBOM generated successfully"

      # Count components
      COMPONENT_COUNT=$(python3 -c "
      import json
      data = json.load(open('sbom.cyclonedx.json'))
      components = data.get('components', [])
      print(len(components))
      ")
      echo "Total components: $COMPONENT_COUNT"

    - |
      echo "Scanning SBOM for known vulnerabilities..."
      grype sbom:sbom.cyclonedx.json -o json > grype-results.json 2>/dev/null || true

      # Parse results
      python3 << 'EOF'
      import json
      import os

      try:
          data = json.load(open('grype-results.json'))
          matches = data.get('matches', [])

          # Count by severity
          severity_counts = {'Critical': 0, 'High': 0, 'Medium': 0, 'Low': 0, 'Negligible': 0}
          for m in matches:
              vuln = m.get('vulnerability', {})
              sev = vuln.get('severity', 'Unknown')
              if sev in severity_counts:
                  severity_counts[sev] += 1

          print(f"Vulnerabilities found: {len(matches)}")
          for sev, count in severity_counts.items():
              if count > 0:
                  print(f"  {sev}: {count}")

          # Write to file for later use
          with open('vuln-counts.txt', 'w') as f:
              f.write(f"VULN_TOTAL={len(matches)}\n")
              f.write(f"VULN_CRITICAL={severity_counts['Critical']}\n")
              f.write(f"VULN_HIGH={severity_counts['High']}\n")

      except Exception as e:
          print(f"Error parsing Grype results: {e}")
          with open('vuln-counts.txt', 'w') as f:
              f.write("VULN_TOTAL=0\n")
              f.write("VULN_CRITICAL=0\n")
              f.write("VULN_HIGH=0\n")
      EOF

    - |
      echo "Analyzing component licenses..."

      python3 << 'EOF'
      import json
      import os

      # Load SBOM
      data = json.load(open('sbom.cyclonedx.json'))
      components = data.get('components', [])

      # Parse denied licenses from env
      deny_licenses_raw = os.environ.get('DENY_LICENSES', '')
      deny_licenses = [l.strip().lower() for l in deny_licenses_raw.split(',') if l.strip()]

      # Common copyleft licenses (restrictive for proprietary use)
      COPYLEFT_LICENSES = [
          'gpl', 'agpl', 'lgpl', 'cc-by-sa', 'mpl', 'cddl', 'epl',
          'osl', 'eupl', 'cecill'
      ]

      # Permissive licenses (generally safe)
      PERMISSIVE_LICENSES = [
          'mit', 'apache', 'bsd', 'isc', 'unlicense', 'cc0', 'wtfpl',
          'zlib', 'boost', 'public domain', '0bsd'
      ]

      license_summary = {
          'permissive': [],
          'copyleft': [],
          'denied': [],
          'unknown': []
      }

      problems = []

      for comp in components:
          name = comp.get('name', 'unknown')
          version = comp.get('version', '?')
          licenses = comp.get('licenses', [])

          if not licenses:
              license_summary['unknown'].append(f"{name}@{version}")
              continue

          for lic in licenses:
              # Handle different license formats in CycloneDX
              if isinstance(lic, dict):
                  lic_id = lic.get('license', {}).get('id', '') or lic.get('license', {}).get('name', '')
                  lic_expression = lic.get('expression', '')
                  lic_str = lic_id or lic_expression
              else:
                  lic_str = str(lic)

              lic_lower = lic_str.lower()

              # Check if denied
              if any(d in lic_lower for d in deny_licenses):
                  license_summary['denied'].append(f"{name}@{version} ({lic_str})")
                  problems.append({
                      'type': 'denied_license',
                      'component': name,
                      'version': version,
                      'license': lic_str
                  })
              # Check if copyleft
              elif any(c in lic_lower for c in COPYLEFT_LICENSES):
                  license_summary['copyleft'].append(f"{name}@{version} ({lic_str})")
                  # Only flag as problem if not explicitly allowed
                  if 'lgpl' not in lic_lower:  # LGPL is often acceptable
                      problems.append({
                          'type': 'copyleft_license',
                          'component': name,
                          'version': version,
                          'license': lic_str
                      })
              # Check if permissive
              elif any(p in lic_lower for p in PERMISSIVE_LICENSES):
                  license_summary['permissive'].append(f"{name}@{version}")
              else:
                  license_summary['unknown'].append(f"{name}@{version} ({lic_str})")

      # Print summary
      print("License Summary:")
      print(f"  Permissive: {len(license_summary['permissive'])}")
      print(f"  Copyleft: {len(license_summary['copyleft'])}")
      print(f"  Denied: {len(license_summary['denied'])}")
      print(f"  Unknown: {len(license_summary['unknown'])}")

      # Save results
      with open('license-analysis.json', 'w') as f:
          json.dump({
              'summary': {k: len(v) for k, v in license_summary.items()},
              'details': license_summary,
              'problems': problems
          }, f, indent=2)

      # Write counts for later
      with open('license-counts.txt', 'w') as f:
          f.write(f"LICENSE_PROBLEMS={len(problems)}\n")
          f.write(f"LICENSE_DENIED={len(license_summary['denied'])}\n")
          f.write(f"LICENSE_COPYLEFT={len(license_summary['copyleft'])}\n")
          f.write(f"LICENSE_UNKNOWN={len(license_summary['unknown'])}\n")
      EOF

    - |
      echo "Generating comprehensive report..."

      python3 << 'EOF'
      import json
      import os
      from datetime import datetime

      # Load all data
      sbom = json.load(open('sbom.cyclonedx.json'))
      grype = json.load(open('grype-results.json')) if os.path.exists('grype-results.json') else {'matches': []}
      licenses = json.load(open('license-analysis.json'))

      # Load counts
      vuln_counts = {}
      if os.path.exists('vuln-counts.txt'):
          for line in open('vuln-counts.txt'):
              k, v = line.strip().split('=')
              vuln_counts[k] = v

      components = sbom.get('components', [])
      vulnerabilities = grype.get('matches', [])

      report = []
      report.append("# SBOM & License Compliance Report")
      report.append(f"\nGenerated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
      report.append(f"Project: {os.environ.get('CI_PROJECT_PATH', 'unknown')}")
      report.append("")

      # Summary table
      report.append("## Summary")
      report.append("")
      report.append("| Metric | Count |")
      report.append("|--------|-------|")
      report.append(f"| Total Components | {len(components)} |")
      report.append(f"| Vulnerabilities | {len(vulnerabilities)} |")
      report.append(f"| Critical/High CVEs | {vuln_counts.get('VULN_CRITICAL', 0)}/{vuln_counts.get('VULN_HIGH', 0)} |")
      report.append(f"| License Issues | {licenses['summary'].get('denied', 0) + licenses['summary'].get('copyleft', 0)} |")
      report.append(f"| Unknown Licenses | {licenses['summary'].get('unknown', 0)} |")
      report.append("")

      # Vulnerabilities section
      if vulnerabilities:
          report.append("## Vulnerabilities")
          report.append("")

          # Group by severity
          by_severity = {}
          for v in vulnerabilities:
              sev = v.get('vulnerability', {}).get('severity', 'Unknown')
              if sev not in by_severity:
                  by_severity[sev] = []
              by_severity[sev].append(v)

          for sev in ['Critical', 'High', 'Medium', 'Low']:
              if sev in by_severity:
                  report.append(f"### {sev} ({len(by_severity[sev])})")
                  report.append("")
                  report.append("| Package | Version | CVE | Fix Available |")
                  report.append("|---------|---------|-----|---------------|")

                  for v in by_severity[sev][:10]:
                      vuln = v.get('vulnerability', {})
                      artifact = v.get('artifact', {})
                      pkg = artifact.get('name', 'unknown')
                      ver = artifact.get('version', '?')
                      cve = vuln.get('id', 'N/A')
                      fix = vuln.get('fix', {}).get('versions', [])
                      fix_str = fix[0] if fix else 'No'

                      report.append(f"| {pkg} | {ver} | {cve} | {fix_str} |")

                  if len(by_severity[sev]) > 10:
                      report.append(f"\n*... and {len(by_severity[sev]) - 10} more {sev.lower()} vulnerabilities*")
                  report.append("")

      # Write report
      with open('sbom-report.md', 'w') as f:
          f.write('\n'.join(report))

      print("Report generated: sbom-report.md")
      EOF

    - |
      # Create issue for critical findings
      source vuln-counts.txt 2>/dev/null || true
      source license-counts.txt 2>/dev/null || true

      if [ "${VULN_CRITICAL:-0}" != "0" ] || [ "${VULN_HIGH:-0}" != "0" ] || [ "${LICENSE_DENIED:-0}" != "0" ]; then
        echo "Creating issue for critical findings..."

        COMPONENT_COUNT=$(python3 -c "import json; print(len(json.load(open('sbom.cyclonedx.json')).get('components', [])))")

        curl -sS -X POST \
          -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"title\": \"SBOM Alert: $(date +%Y-%m-%d) - ${VULN_CRITICAL:-0} critical, ${LICENSE_DENIED:-0} license issues\",
            \"description\": \"## SBOM & License Compliance Alert\n\nThe weekly SBOM scan has identified issues requiring attention.\n\n### Summary\n- **Critical Vulnerabilities**: ${VULN_CRITICAL:-0}\n- **High Vulnerabilities**: ${VULN_HIGH:-0}\n- **Denied Licenses**: ${LICENSE_DENIED:-0}\n- **Total Components**: ${COMPONENT_COUNT}\n\n### Full Report\nSee the job artifacts for detailed reports.\n\n### Recommended Actions\n1. Review critical and high vulnerabilities for exploitability\n2. Update affected dependencies to patched versions\n3. Review license conflicts for compliance requirements\n\n---\n*Generated by repo-sapiens weekly SBOM workflow*\",
            \"labels\": \"security,dependencies,automated\"
          }" \
          "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/issues" || echo "Issue creation failed"
      fi

  artifacts:
    paths:
      - sbom.cyclonedx.json
      - sbom.spdx.json
      - sbom.syft.json
      - grype-results.json
      - license-analysis.json
      - sbom-report.md
    expire_in: 90 days
    when: always
  resource_group: sapiens-sbom
