# @repo-sapiens-template
# @version: 1.1.0
# @name: weekly-test-coverage
#
# Weekly Test Coverage Improvement for GitLab CI
#
# Runs weekly to analyze test coverage and create MRs with new tests
# for under-covered modules.
#
# Setup:
# 1. Copy to .gitlab-ci.yml (or include via `include:`)
# 2. Set required CI/CD variables:
#    - SAPIENS_GITLAB_TOKEN: GitLab API token
#    - SAPIENS_CLAUDE_API_KEY: Claude API key (if using claude-api agent)
# 3. Create a pipeline schedule: Settings > CI/CD > Schedules (e.g., every Monday at 9am)
# 4. Adjust target coverage as needed

stages:
  - coverage

default:
  interruptible: true

variables:
  TARGET_COVERAGE: "60"
  PYTHON_VERSION: "3.12"

improve-coverage:
  stage: coverage
  image: python:${PYTHON_VERSION}-slim
  timeout: 30 minutes
  rules:
    # Run on schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Allow manual trigger
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  variables:
    # Note: GITLAB_ prefix is reserved, so we source from SAPIENS_GITLAB_TOKEN
    GITLAB_TOKEN: $SAPIENS_GITLAB_TOKEN
    AUTOMATION__GIT_PROVIDER__BASE_URL: $CI_SERVER_URL
    AUTOMATION__GIT_PROVIDER__API_TOKEN: $SAPIENS_GITLAB_TOKEN
    AUTOMATION__REPOSITORY__OWNER: $CI_PROJECT_NAMESPACE
    AUTOMATION__REPOSITORY__NAME: $CI_PROJECT_NAME
    AUTOMATION__AGENT_PROVIDER__API_KEY: $SAPIENS_CLAUDE_API_KEY
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - pip install --quiet --no-cache-dir repo-sapiens
    - pip install -e ".[dev]" 2>/dev/null || pip install -e . pytest pytest-cov 2>/dev/null || true
    - git config user.name "gitlab-ci[bot]"
    - git config user.email "gitlab-ci[bot]@users.noreply.gitlab.com"
  script:
    - |
      # Run tests with coverage
      echo "Running coverage analysis..."
      python -m pytest tests/ --cov --cov-report=json --cov-report=term -q || true

      # Extract coverage summary
      if [ -f coverage.json ]; then
        TOTAL=$(python -c "import json; d=json.load(open('coverage.json')); print(d['totals']['percent_covered'])")
        echo "Current coverage: $TOTAL%"
      else
        TOTAL="0"
        echo "No coverage data found"
      fi

      # Create improvement branch
      BRANCH="auto/improve-coverage-$(date +%Y%m%d)"
      git checkout -b "$BRANCH"

      # Run sapiens to improve coverage
      sapiens task "Improve test coverage for this Python project.

      Current total coverage: ${TOTAL}%
      Target coverage: ${TARGET_COVERAGE}%

      Tasks:
      1. Read coverage.json to identify files with lowest coverage
      2. Pick ONE module with coverage below ${TARGET_COVERAGE}% to improve
      3. Read the source file to understand what needs testing
      4. Write comprehensive unit tests for uncovered code paths
      5. Run the tests to verify they pass: python -m pytest tests/ -v

      Guidelines:
      - Focus on one module at a time for reviewable MRs
      - Write meaningful tests, not just coverage padding
      - Include edge cases and error conditions
      - Follow existing test patterns in the codebase

      Commit your changes with message: 'test: Add tests for [module name]'"

      # Check if there are changes to commit
      git add -A
      if git diff --staged --quiet; then
        echo "No test changes made"
        exit 0
      fi

      # Commit and push
      git commit -m "test: Improve test coverage" || true
      git push -u origin "$BRANCH" || exit 1

      # Create MR via API
      curl -sS -X POST \
        -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{
          \"source_branch\": \"$BRANCH\",
          \"target_branch\": \"main\",
          \"title\": \"test: Improve test coverage\",
          \"description\": \"## Summary\nAutomated MR to improve test coverage.\n\nCurrent coverage: ${TOTAL}%\n\n---\n*Generated by repo-sapiens weekly test coverage workflow.*\",
          \"remove_source_branch\": true
        }" \
        "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/merge_requests" || echo "MR creation failed or already exists"
  artifacts:
    paths:
      - coverage.json
    expire_in: 7 days
    when: always
  resource_group: sapiens-coverage
