# @repo-sapiens-template
# @version: 1.0.0
# @name: weekly-dependency-audit
#
# Weekly Dependency Audit for GitLab CI/CD
#
# Checks for outdated dependencies, security vulnerabilities, and
# creates MRs for safe updates.
#
# Setup:
# 1. Copy to .gitlab-ci.yml (or include via `include:`)
# 2. Set required CI/CD variables (Settings > CI/CD > Variables):
#    - SAPIENS_GITLAB_TOKEN: GitLab API token with repo/MR write access (note: GITLAB_ prefix is reserved)
#    - SAPIENS_AI_API_KEY: Claude API key (masked, protected)
# 3. Set up a weekly pipeline schedule (CI/CD > Schedules)

variables:
  PYTHON_VERSION: "3.12"
  PIP_NO_CACHE_DIR: "1"

stages:
  - audit
  - update

default:
  interruptible: true

audit-dependencies:
  stage: audit
  image: python:${PYTHON_VERSION}-slim
  timeout: 15 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  before_script:
    - pip install --quiet --no-cache-dir pip-audit safety
  script:
    - |
      echo "## Outdated Packages" > dependency-report.md
      pip list --outdated --format=json > outdated.json 2>/dev/null || echo "[]" > outdated.json

      python -c "
      import json
      data = json.load(open('outdated.json'))
      if data:
          print('| Package | Current | Latest |')
          print('|---------|---------|--------|')
          for p in data[:20]:
              print(f\"| {p['name']} | {p['version']} | {p['latest_version']} |\")
      else:
          print('All packages are up to date!')
      " >> dependency-report.md

      echo -e "\n## Security Vulnerabilities" >> dependency-report.md
      pip-audit --format=json > audit.json 2>/dev/null || echo "[]" > audit.json

      python -c "
      import json
      try:
          data = json.load(open('audit.json'))
          if data:
              print('| Package | Vulnerability | Fix Version |')
              print('|---------|---------------|-------------|')
              for v in data[:10]:
                  fix = v.get('fix_versions', ['N/A'])
                  print(f\"| {v.get('name', 'unknown')} | {v.get('id', 'N/A')} | {fix[0] if fix else 'N/A'} |\")
          else:
              print('No known vulnerabilities found!')
      except:
          print('Security audit completed - check logs for details')
      " >> dependency-report.md

      # Check if there are issues to fix
      OUTDATED_COUNT=$(cat outdated.json | python -c "import json,sys; print(len(json.load(sys.stdin)))")
      VULN_COUNT=$(cat audit.json | python -c "import json,sys; d=json.load(sys.stdin); print(len(d) if isinstance(d, list) else 0)")

      echo "OUTDATED_COUNT=$OUTDATED_COUNT" >> build.env
      echo "VULN_COUNT=$VULN_COUNT" >> build.env
  artifacts:
    paths:
      - dependency-report.md
      - outdated.json
      - audit.json
    reports:
      dotenv: build.env
    expire_in: 30 days

update-dependencies:
  stage: update
  image: python:${PYTHON_VERSION}-slim
  timeout: 30 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  needs:
    - job: audit-dependencies
      artifacts: true
  variables:
    # Note: GITLAB_ prefix is reserved, so we source from SAPIENS_GITLAB_TOKEN
    GITLAB_TOKEN: $SAPIENS_GITLAB_TOKEN
    AUTOMATION__AGENT_PROVIDER__API_KEY: $SAPIENS_AI_API_KEY
  before_script:
    - pip install --quiet --no-cache-dir repo-sapiens
    - apt-get update && apt-get install -y git
  script:
    - |
      if [ "$OUTDATED_COUNT" = "0" ] && [ "$VULN_COUNT" = "0" ]; then
        echo "No dependency updates needed"
        exit 0
      fi

      git config user.name "gitlab-ci[bot]"
      git config user.email "gitlab-ci[bot]@users.noreply.gitlab.com"

      BRANCH="auto/dependency-audit-$(date +%Y%m%d)"
      git checkout -b "$BRANCH"

      sapiens task "Review the dependency audit report and update safe dependencies.

      $(cat dependency-report.md)

      Tasks:
      1. Review outdated.json for packages that can be safely updated
      2. Prioritize security fixes from audit.json
      3. For PATCH and MINOR updates of well-known packages, update them
      4. For MAJOR updates, only update if there are security issues
      5. Update pyproject.toml or requirements.txt with new versions
      6. Run tests to verify nothing breaks: python -m pytest tests/ -x

      Guidelines:
      - Be conservative - only update what's safe
      - Skip updates that break tests
      - Group related updates together
      - Note any packages that need manual review

      Commit changes with: 'chore(deps): Update dependencies [audit]'"

      git add -A
      if ! git diff --staged --quiet; then
        git commit -m "chore(deps): Weekly dependency updates"
        git push -u origin "$BRANCH" || echo "Push failed"

        # Create MR via API
        curl --silent --request POST \
          --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
          --header "Content-Type: application/json" \
          --data "{
            \"source_branch\": \"$BRANCH\",
            \"target_branch\": \"${CI_DEFAULT_BRANCH}\",
            \"title\": \"chore(deps): Weekly dependency updates\",
            \"description\": \"## Dependency Audit Report\n\n$(cat dependency-report.md | head -50 | sed 's/"/\\"/g')\n\n---\nGenerated by repo-sapiens weekly dependency audit.\",
            \"labels\": \"dependencies,automated\"
          }" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests" || echo "MR creation failed"
      else
        echo "No changes made"
      fi
  allow_failure: true
