# @repo-sapiens-template
# @version: 1.0.0
# @name: weekly-security-review
#
# Weekly Security Review for GitLab CI/CD
#
# Runs comprehensive security scans for configured languages, generates a report,
# and automatically fixes identified vulnerabilities where safe to do so.
#
# Supported Languages: Python, Go, Java, C++, C#, Kotlin, Clojure, Rust, TypeScript, JavaScript
#
# Setup:
# 1. Copy to .gitlab-ci.yml (or include via `include:`)
# 2. Set required CI/CD variables (Settings > CI/CD > Variables):
#    - GITLAB_TOKEN: GitLab API token with repo write access
#    - ANTHROPIC_API_KEY: Claude API key (masked, protected)
# 3. Configure SECURITY_LANGUAGES below with your project's languages
# 4. Set up a pipeline schedule (CI/CD > Schedules) for weekly runs
#
# Note: GitLab scheduled pipelines are configured via the UI, not cron in YAML.
# Go to: Settings > CI/CD > Pipeline schedules > New schedule

variables:
  PYTHON_VERSION: "3.12"
  # Configure which languages to scan (space-separated)
  # Options: python go java cpp csharp kotlin clojure rust typescript javascript
  SECURITY_LANGUAGES: "{{SECURITY_LANGUAGES}}"
  PIP_NO_CACHE_DIR: "1"

stages:
  - scan
  - report
  - fix

default:
  interruptible: true

# Python Security Scanning
python-security:
  stage: scan
  image: python:${PYTHON_VERSION}-slim
  timeout: 15 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  variables:
    SCAN_LANGUAGE: python
  before_script:
    - pip install --quiet bandit pip-audit
  script:
    - |
      echo "## Python Security (Bandit)" > python-security.md
      if ls *.py &>/dev/null || [ -d "src" ] || [ -d "lib" ]; then
        bandit -r . -f json -o bandit-results.json --exclude .venv,venv,node_modules,dist,build 2>/dev/null || true
        if [ -f bandit-results.json ]; then
          python -c "
      import json
      data = json.load(open('bandit-results.json'))
      results = data.get('results', [])
      print(f'Issues found: {len(results)}')
      for r in results[:10]:
          print(f\"[{r.get('issue_severity')}/{r.get('issue_confidence')}] {r.get('filename')}:{r.get('line_number')}\")
          print(f\"  {r.get('issue_text')}\")
      "
        fi
      else
        echo "No Python files found"
      fi
    - |
      echo "## Python Dependencies (pip-audit)" >> python-security.md
      if [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
        pip-audit --format=json --output=pip-audit-results.json 2>/dev/null || true
      fi
  artifacts:
    paths:
      - python-security.md
      - bandit-results.json
      - pip-audit-results.json
    expire_in: 30 days
    when: always
  only:
    variables:
      - $SECURITY_LANGUAGES =~ /python/

# Go Security Scanning
go-security:
  stage: scan
  image: golang:1.22
  timeout: 15 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  before_script:
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - go install golang.org/x/vuln/cmd/govulncheck@latest
  script:
    - |
      echo "## Go Security (gosec)" > go-security.md
      if [ -f "go.mod" ]; then
        gosec -fmt=json -out=gosec-results.json ./... 2>/dev/null || true
        govulncheck -json ./... > govulncheck-results.json 2>/dev/null || true
      else
        echo "No Go module found"
      fi
  artifacts:
    paths:
      - go-security.md
      - gosec-results.json
      - govulncheck-results.json
    expire_in: 30 days
    when: always
  only:
    variables:
      - $SECURITY_LANGUAGES =~ /go/

# Node.js/TypeScript Security Scanning
nodejs-security:
  stage: scan
  image: node:20-slim
  timeout: 15 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  script:
    - |
      echo "## JavaScript/TypeScript Dependencies (npm audit)" > nodejs-security.md
      if [ -f "package.json" ]; then
        npm audit --json > npm-audit-results.json 2>/dev/null || true
      else
        echo "No package.json found"
      fi
  artifacts:
    paths:
      - nodejs-security.md
      - npm-audit-results.json
    expire_in: 30 days
    when: always
  only:
    variables:
      - $SECURITY_LANGUAGES =~ /(typescript|javascript)/

# Generate consolidated report
generate-report:
  stage: report
  image: python:${PYTHON_VERSION}-slim
  timeout: 10 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  script:
    - |
      echo "# Security Review Report" > security-report.md
      echo "Generated: $(date -u '+%Y-%m-%d %H:%M UTC')" >> security-report.md
      echo "Project: ${CI_PROJECT_PATH}" >> security-report.md
      echo "" >> security-report.md

      TOTAL=0

      # Aggregate Python results
      if [ -f bandit-results.json ]; then
        COUNT=$(python3 -c "import json; d=json.load(open('bandit-results.json')); print(len(d.get('results', [])))" 2>/dev/null || echo 0)
        echo "| Bandit (Python) | $COUNT |" >> security-report.md
        TOTAL=$((TOTAL + COUNT))
      fi

      if [ -f pip-audit-results.json ] && [ -s pip-audit-results.json ]; then
        COUNT=$(python3 -c "import json; print(len(json.load(open('pip-audit-results.json'))))" 2>/dev/null || echo 0)
        echo "| pip-audit (Python deps) | $COUNT |" >> security-report.md
        TOTAL=$((TOTAL + COUNT))
      fi

      if [ -f gosec-results.json ]; then
        COUNT=$(python3 -c "import json; d=json.load(open('gosec-results.json')); print(len(d.get('Issues', [])))" 2>/dev/null || echo 0)
        echo "| gosec (Go) | $COUNT |" >> security-report.md
        TOTAL=$((TOTAL + COUNT))
      fi

      if [ -f npm-audit-results.json ]; then
        COUNT=$(python3 -c "import json; d=json.load(open('npm-audit-results.json')); print(len(d.get('vulnerabilities',{})))" 2>/dev/null || echo 0)
        echo "| npm audit (JS/TS) | $COUNT |" >> security-report.md
        TOTAL=$((TOTAL + COUNT))
      fi

      echo "" >> security-report.md
      echo "**Total issues: $TOTAL**" >> security-report.md

      echo "TOTAL_ISSUES=$TOTAL" >> build.env
  artifacts:
    paths:
      - security-report.md
    reports:
      dotenv: build.env
    expire_in: 30 days

# Auto-fix security issues (optional)
auto-fix-security:
  stage: fix
  image: python:${PYTHON_VERSION}-slim
  timeout: 30 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  needs:
    - job: generate-report
      artifacts: true
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    AUTOMATION__AGENT_PROVIDER__API_KEY: $ANTHROPIC_API_KEY
  before_script:
    - pip install --quiet --no-cache-dir repo-sapiens
    - apt-get update && apt-get install -y git
  script:
    - |
      if [ "$TOTAL_ISSUES" = "0" ]; then
        echo "No security issues found, skipping auto-fix"
        exit 0
      fi

      git config user.name "gitlab-ci[bot]"
      git config user.email "gitlab-ci[bot]@users.noreply.gitlab.com"

      BRANCH="auto/security-fixes-$(date +%Y%m%d)"
      git checkout -b "$BRANCH"

      sapiens task "Review the security report and fix identified vulnerabilities.

      $(cat security-report.md)

      Tasks:
      1. Review each security finding
      2. For dependency vulnerabilities, update to fixed versions
      3. For code vulnerabilities, apply safe fixes
      4. Run tests after fixes if available
      5. Skip fixes that are false positives or require major refactoring

      Commit format: 'security: Fix [vulnerability type] in [file/module]'"

      git add -A
      if ! git diff --staged --quiet; then
        git commit -m "security: Weekly security fixes"
        git push -u origin "$BRANCH" || echo "Push failed"

        # Create MR via API
        curl --silent --request POST \
          --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
          --header "Content-Type: application/json" \
          --data "{
            \"source_branch\": \"$BRANCH\",
            \"target_branch\": \"${CI_DEFAULT_BRANCH}\",
            \"title\": \"security: Weekly security fixes ($(date +%Y-%m-%d))\",
            \"description\": \"$(cat security-report.md | head -100 | jq -Rs .)\",
            \"labels\": \"security,automated\"
          }" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests" || echo "MR creation failed"
      fi
  allow_failure: true
