# @repo-sapiens-template
# @version: 1.1.0
# @name: post-merge-docs
#
# Post-Merge Documentation Update for GitHub Actions
#
# Automatically reviews changes after merges to main and updates
# documentation if needed (README, CHANGELOG, API docs).
#
# Setup:
# 1. Copy to .github/workflows/post-merge-docs.yaml
# 2. Set required secrets:
#    - ANTHROPIC_API_KEY: Claude API key (or configure for Ollama)
# 3. Customize the task prompt as needed

name: Update Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    # Skip if commit message contains [skip docs] or [no docs]
    if: |
      !contains(github.event.head_commit.message, '[skip docs]') &&
      !contains(github.event.head_commit.message, '[no docs]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10  # Get recent history for context
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install repo-sapiens
        run: pip install repo-sapiens

      - name: Get recent changes
        id: changes
        run: |
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          git log --oneline -5 >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          sapiens react "Review the recent commits and update documentation if needed.

          Recent commits:
          ${{ steps.changes.outputs.commits }}

          Tasks:
          1. Check if README.md needs updates for any new features or changed behavior
          2. Add CHANGELOG.md entries for notable changes (if not already present)
          3. Update any API documentation if function signatures changed
          4. Fix any broken links or outdated examples

          Only make changes if genuinely needed. If no updates required, just finish.
          If changes are made, commit them with message: 'docs: Update documentation [skip docs]'"

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "docs: Auto-update documentation [skip docs]"
          git push || echo "No changes to push"
