name: Approved

# Triggers when 'approved' label is added to an issue or PR
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  process-approval:
    name: Process Approval
    # Note: Gitea sets github.event.label to null, use labels array instead
    if: contains(github.event.issue.labels.*.name, 'approved') || contains(github.event.pull_request.labels.*.name, 'approved')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SAPIENS_GITEA_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install sapiens
        run: pip install -e .

      - name: Process approval
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ github.server_url }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ github.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ github.event.repository.name }}
          # For ollama - pass base URL (no API key needed)
          AUTOMATION__AGENT_PROVIDER__BASE_URL: ${{ secrets.SAPIENS_OLLAMA_URL }}
        run: |
          ISSUE_NUM="${{ github.event.issue.number }}${{ github.event.pull_request.number }}"
          echo "✅ Processing approval for #${ISSUE_NUM}"
          sapiens --config sapiens_config.ci.yaml process-issue --issue ${ISSUE_NUM} --system-prompt .gitea/workflows/sapiens/prompts/approved.md
