# @repo-sapiens-template
# @version: 1.1.0
# @name: automation-daemon
#
# Sapiens Automation Daemon for Gitea Actions
#
# This workflow runs repo-sapiens periodically to process issues automatically.
#
# Setup:
# 1. Copy this file to .gitea/workflows/automation-daemon.yaml
# 2. Set required secrets in your repo settings:
#    - SAPIENS_GITEA_TOKEN: Your Gitea API token
#      (Note: Gitea reserves GITEA_* prefix for internal use)
#    - OPENAI_API_KEY: (if using Goose with OpenAI)
#    - ANTHROPIC_API_KEY or CLAUDE_API_KEY: (if using Claude)
# 3. Update CONFIG_FILE to match your config

name: Sapiens Daemon

on:
  # schedule:
  #   - cron: '*/5 * * * *'  # Every 5 minutes (disabled by default)
  workflow_dispatch:  # Manual trigger only

env:
  # CI-specific config (separates CI settings from local development config)
  CONFIG_FILE: sapiens_config.ci.yaml

jobs:
  process-pending:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install repo-sapiens
        run: |
          pip install repo-sapiens
          # If using Goose, also install it:
          # pip install goose-ai

      - name: Process all pending issues
        env:
          # Git provider credentials
          GITEA_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          GITEA_API_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}

          # AI provider credentials (uncomment the one you use)
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          sapiens --config $CONFIG_FILE process-all --log-level INFO

      - name: Upload state artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workflow-state-${{ github.run_number }}
          path: .automation/state/
          retention-days: 7
