name: Create Fix Proposal

# Triggers when 'needs-fix' label is added after code review
on:
  issues:
    types: [labeled]

jobs:
  create-fix-proposal:
    name: Generate Fix Proposal
    # Note: Gitea sets github.event.label to null, use labels array instead
    if: contains(github.event.issue.labels.*.name, 'needs-fix')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install sapiens
        run: pip install -e .

      - name: Create fix proposal
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ github.server_url }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ github.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ github.event.repository.name }}
          # For ollama - pass base URL (no API key needed)
          AUTOMATION__AGENT_PROVIDER__BASE_URL: ${{ secrets.SAPIENS_OLLAMA_URL }}
        run: |
          echo "🔧 Creating fix proposal for issue/PR #${{ github.event.issue.number }}"
          sapiens --config sapiens_config.ci.yaml process-issue --issue ${{ github.event.issue.number }} --system-prompt .gitea/workflows/sapiens/prompts/needs-fix.md

      - name: Post success comment
        if: success()
        env:
          GITEA_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
        run: |
          curl -sS -X POST \
            -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"body": "🔧 **Fix proposal created!**\n\nReview the proposed fixes and add the `approved` label to apply them.\n\n◆ Posted by Sapiens Automation"}' \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
