name: Code Review

# Triggers when 'needs-review' label is added
on:
  issues:
    types: [labeled]

jobs:
  code-review:
    name: Automated Code Review
    # Note: Gitea sets github.event.label to null, use labels array instead
    if: contains(github.event.issue.labels.*.name, 'needs-review')
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install sapiens
        run: pip install -e .

      - name: Run code review
        env:
          AUTOMATION__GIT_PROVIDER__BASE_URL: ${{ github.server_url }}
          AUTOMATION__GIT_PROVIDER__API_TOKEN: ${{ secrets.SAPIENS_GITEA_TOKEN }}
          AUTOMATION__REPOSITORY__OWNER: ${{ github.repository_owner }}
          AUTOMATION__REPOSITORY__NAME: ${{ github.event.repository.name }}
          AUTOMATION__AGENT_PROVIDER__API_KEY: ${{ secrets.SAPIENS_CLAUDE_API_KEY }}
        run: |
          echo "🔍 Running code review for issue/PR #${{ github.event.issue.number }}"
          sapiens --config sapiens_config.ci.yaml process-issue --issue ${{ github.event.issue.number }} --system-prompt .gitea/workflows/sapiens/prompts/needs-review.md

      - name: Upload review artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: review-artifacts-${{ github.event.issue.number }}
          path: .automation/reviews/
          retention-days: 30
